name: ARCCfnrelease

on:
  workflow_dispatch:
  

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-test:
    permissions:
      contents: read
      
    runs-on: self-hosted
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            *.cloudfront.net:443
            github.com:443
            *.docker.com:443
            *.docker.io:443
            *.golang.org:443
            *.cloudflare.docker.com:443
            public.ecr.aws:443
            storage.googleapis.com:443
            docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com:443
          
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          docker build .
          
