name: ARCK8SCfnrelease
run-name:  ARCK8SCfnrelease-${{ inputs.WorkflowFileID }}

on:
  workflow_dispatch:
    inputs:
      RunnerLabel:
        description: "Target ARC name used for runs-on in job"
        required: true
        default: "arc0"
      WorkflowFileID:
        description: "WorkflowID"
        required: false
        default: ""
  

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-test-arc-k8s:
    permissions:
      contents: read
      
    runs-on: ${{ inputs.RunnerLabel }}
    container: ubuntu
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com.local:443
            api.github.com:443
            archive.ubuntu.com:80
            auth.docker.io:443
            codeload.github.com.local:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            security.ubuntu.com:80

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl git
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: curl https://google.com
      # - name: Build docker image
      #   run: |
      #     docker build .
          
      # - name: test outbound
      #   continue-on-error: true
      #   run: |
      #     docker run alpine:3.15 wget http://52.200.117.68
