name: ARCCfnrelease
run-name: ARCCfnrelease-${{ inputs.WorkflowFileID }}


on:
  workflow_dispatch:
    inputs:
      RunnerLabel:
        description: "Target ARC name used for runs-on in job"
        required: true
        default: "self-hosted"
      WorkflowFileID:
        description: "WorkflowID"
        required: false
        default: ""
  

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-test:
    permissions:
      contents: read
      
    runs-on: ${{ inputs.RunnerLabel }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            *.cloudfront.net:443
            github.com:443
            *.docker.com:443
            *.docker.io:443
            *.golang.org:443
            *.cloudflare.docker.com:443
            public.ecr.aws:443
            storage.googleapis.com:443
            docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com:443
            *.local:443
          
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          docker build .

      - name: Compress tcpdump
        if: always()
        continue-on-error: true
        run: |
          gzip ${{ runner.temp }}/dump-${{ runner.name }}.pcap
          
      - name: Upload tcpdump
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: dump-${{ runner.name }}
          path: ${{ runner.temp }}/dump-${{ runner.name }}.pcap.gz
          compression-level: 0
          retention-days: 1          
