name: ARCK8SCfnrelease

on:
  workflow_dispatch:
    inputs:
      RunnerLabel:
        description: "Target ARC name used for runs-on in job"
        required: true
        default: "arc0"
  

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-test-arc-k8s:
    permissions:
      contents: read
      
    runs-on: ${{ inputs.RunnerLabel }}
    container: ubuntu
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            *.cloudfront.net:443
            github.com:443
            *.docker.com:443
            *.docker.io:443
            *.golang.org:443
            *.cloudflare.docker.com:443
            public.ecr.aws:443
            storage.googleapis.com:443
          
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
        with:
          fetch-depth: 0
      - run: curl https://google.com
      # - name: Build docker image
      #   run: |
      #     docker build .
          
      # - name: test outbound
      #   continue-on-error: true
      #   run: |
      #     docker run alpine:3.15 wget http://52.200.117.68
